export const featuredResources = [
  {
    id: 1,
    name: "ChatGPT 中文镜像站",
    description: "无需魔法访问的 ChatGPT 镜像站，支持 GPT-4，体验稳定快速。",
    tags: ["AI工具", "效率办公"],
    rating: 4.9,
    collections: 32100,
    badge: "推荐",
    bgColor: "from-gray-900 to-gray-800",
    logoText: "ChatGPT",
    logoIcon: "🤖",
  },
  {
    id: 2,
    name: "Canva 可画官网",
    description: "在线设计平台，海量模板，轻松做出精美设计。",
    tags: ["设计工具", "设计素材"],
    rating: 4.8,
    collections: 28700,
    bgColor: "from-blue-900 to-cyan-900",
    logoText: "Canva可画",
    logoIcon: "🎨",
  },
  {
    id: 3,
    name: "Vercel 部署平台",
    description: "前端开发者的最佳部署平台，支持多种框架，极速上线。",
    tags: ["开发工具", "部署托管"],
    rating: 4.7,
    collections: 18900,
    bgColor: "from-gray-900 to-black",
    logoText: "▲ Vercel",
    logoIcon: "▲",
  },
  {
    id: 4,
    name: "Pexels 高清图库",
    description: "免费可商用的高清图片和视频素材库，无需署名。",
    tags: ["图片素材", "视频素材"],
    rating: 4.8,
    collections: 21300,
    bgColor: "from-green-900 to-teal-900",
    logoText: "Pexels",
    logoIcon: "🖼️",
  },
];

export const hotRankings = [
  { rank: 1, name: "ChatGPT", category: "AI工具", score: 9.8 },
  { rank: 2, name: "Notion", category: "效率办公", score: 9.6 },
  { rank: 3, name: "Midjourney", category: "AI绘画", score: 9.5 },
  { rank: 4, name: "Canva 可画", category: "设计工具", score: 9.4 },
  { rank: 5, name: "Vercel", category: "开发工具", score: 9.3 },
  { rank: 6, name: "小红书数据分析", category: "运营工具", score: 9.2 },
  { rank: 7, name: "哔哩哔哩", category: "学习网站", score: 9.1 },
  { rank: 8, name: "Flaticon 图标库", category: "设计素材", score: 9.0 },
  { rank: 9, name: "剪映专业版", category: "视频工具", score: 8.9 },
  { rank: 10, name: "知乎", category: "知识社区", score: 8.8 },
];

export const categories = [
  { name: "AI工具", count: 1234, icon: "🤖", color: "text-purple-400" },
  { name: "设计素材", count: 1860, icon: "🎨", color: "text-pink-400" },
  { name: "开发工具", count: 1520, icon: "💻", color: "text-blue-400" },
  { name: "营销运营", count: 980, icon: "📈", color: "text-green-400" },
  { name: "学习网站", count: 1120, icon: "🎓", color: "text-yellow-400" },
  { name: "效率办公", count: 1350, icon: "⚡", color: "text-orange-400" },
  { name: "视频素材", count: 870, icon: "🎬", color: "text-red-400" },
  { name: "导航合集", count: 660, icon: "🧭", color: "text-cyan-400" },
];

export const featuredTopics = [
  {
    id: 1,
    title: "AI工具大合集",
    description: "精选全球热门AI工具，提升效率与创造力",
    count: 68,
    color: "from-purple-600 to-blue-600",
    icon: "🤖",
  },
  {
    id: 2,
    title: "设计师必备资源",
    description: "设计素材、灵感网站，一站式集合",
    count: 72,
    color: "from-pink-600 to-rose-600",
    icon: "🎨",
  },
  {
    id: 3,
    title: "程序员效率工具箱",
    description: "开发、调试、测试，高效开发必备",
    count: 56,
    color: "from-blue-600 to-cyan-600",
    icon: "⚙️",
  },
  {
    id: 4,
    title: "副业赚钱指南",
    description: "精选副业项目与资源，开启你的第二收入",
    count: 45,
    color: "from-amber-600 to-orange-600",
    icon: "💰",
  },
];

export const marketplaceResources = [
  {
    id: 1,
    name: "Figma",
    description: "在线 UI/UX 设计协作工具，支持实时协作与原型设计。",
    tags: ["设计", "协作", "原型"],
    rating: 4.9,
    collections: 32100,
    logo: "🎯",
    logoBg: "bg-purple-600",
  },
  {
    id: 2,
    name: "Notion",
    description: "一体化知识管理与协作平台，文档、任务、数据库全能。",
    tags: ["效率", "笔记", "协作"],
    rating: 4.8,
    collections: 28700,
    logo: "N",
    logoBg: "bg-gray-800",
  },
  {
    id: 3,
    name: "GitHub",
    description: "全球领先的代码托管平台，支持开源协作与版本管理。",
    tags: ["开发", "代码托管", "开源"],
    rating: 4.9,
    collections: 45600,
    logo: "🐙",
    logoBg: "bg-gray-900",
  },
  {
    id: 4,
    name: "Hugging Face",
    description: "领先的 AI 模型与数据集社区，探索和构建机器学习应用。",
    tags: ["AI", "模型", "开源"],
    rating: 4.8,
    collections: 23400,
    logo: "🤗",
    logoBg: "bg-yellow-600",
  },
  {
    id: 5,
    name: "Dribbble",
    description: "设计师作品展示社区，发现优质设计灵感与作品。",
    tags: ["设计", "灵感", "作品集"],
    rating: 4.7,
    collections: 19600,
    logo: "🏀",
    logoBg: "bg-pink-600",
  },
  {
    id: 6,
    name: "Pexels",
    description: "免费高清图片与视频素材库，适用于各类创意项目。",
    tags: ["素材", "图片", "免费"],
    rating: 4.8,
    collections: 21300,
    logo: "📸",
    logoBg: "bg-green-600",
  },
  {
    id: 7,
    name: "Vercel",
    description: "前端应用部署与托管平台，专为现代 Web 打造。",
    tags: ["开发", "部署", "前端"],
    rating: 4.7,
    collections: 18900,
    logo: "▲",
    logoBg: "bg-black",
  },
  {
    id: 8,
    name: "飞书文档",
    description: "多端协同的在线文档与知识库，团队协作更高效。",
    tags: ["效率", "文档", "协作"],
    rating: 4.8,
    collections: 17200,
    logo: "📋",
    logoBg: "bg-blue-600",
  },
  {
    id: 9,
    name: "剪映",
    description: "专业易用的视频剪辑工具，轻松创作高质量视频。",
    tags: ["视频", "剪辑", "创作"],
    rating: 4.8,
    collections: 15600,
    logo: "✂️",
    logoBg: "bg-red-600",
  },
];

export const topicCollections = [
  {
    id: 1,
    title: "AI写作与内容生成",
    description: "精选 AI 写作、文案生成、语法优化、翻译等高质量内容。",
    category: "AI工具",
    count: 86,
    updateDays: 2,
    logo: "✍️",
    logoBg: "bg-purple-600",
  },
  {
    id: 2,
    title: "设计师必备资源库",
    description: "图标、插画、样机、配色、字体等设计资源，一站式满足高品质输出。",
    category: "设计资源",
    count: 156,
    updateDays: 1,
    logo: "🎨",
    logoBg: "bg-pink-600",
  },
  {
    id: 3,
    title: "前端开发资源精选",
    description: "前端框架、组件库、工具链、学习资料等，帮助高效构建现代化 Web 应用。",
    category: "开发工具",
    count: 132,
    updateDays: 3,
    logo: "💻",
    logoBg: "bg-blue-600",
  },
  {
    id: 4,
    title: "编程学习路线图",
    description: "从入门到进阶，系统化学习路线与优质教程，帮助你成为更好的开发者。",
    category: "学习提升",
    count: 98,
    updateDays: 5,
    logo: "📚",
    logoBg: "bg-green-600",
  },
  {
    id: 5,
    title: "效率办公工具大全",
    description: "任务管理、笔记整理、协同办公、自动化工具，让工作更高效。",
    category: "效率办公",
    count: 112,
    updateDays: 2,
    logo: "⚡",
    logoBg: "bg-yellow-600",
  },
  {
    id: 6,
    title: "副业赚钱项目合集",
    description: "精选可落地的副业项目与变现思路，帮你开启第二收入曲线。",
    category: "副业项目",
    count: 78,
    updateDays: 4,
    logo: "💰",
    logoBg: "bg-amber-600",
  },
  {
    id: 7,
    title: "自媒体与内容创作",
    description: "选题、脚本、前端、运营全流程资源，帮你打造涨粉变现内容。",
    category: "自媒体",
    count: 93,
    updateDays: 3,
    logo: "📱",
    logoBg: "bg-red-600",
  },
  {
    id: 8,
    title: "优质开源项目推荐",
    description: "精选高质量开源项目与实用工具，学习优秀代码，提升开发水平。",
    category: "开源资源",
    count: 145,
    updateDays: 6,
    logo: "🐙",
    logoBg: "bg-indigo-600",
  },
];

export const rankingsData = [
  {
    rank: 1,
    name: "ChatGPT",
    description: "先进的 AI 对话助手，支持创作、编程、翻译等多种场景。",
    category: "AI工具",
    tags: ["AI工具", "聊天机器人"],
    rating: 4.9,
    heat: 32100,
    trend: "+5.2%",
    logo: "🤖",
    logoBg: "bg-green-600",
  },
  {
    rank: 2,
    name: "Notion",
    description: "结构化知识管理与协作平台，文档、任务、数据库全能。",
    category: "效率办公",
    tags: ["效率", "协作", "笔记"],
    rating: 4.8,
    heat: 28700,
    trend: "+3.8%",
    logo: "N",
    logoBg: "bg-gray-800",
  },
  {
    rank: 3,
    name: "Midjourney",
    description: "顶级 AI 绘图工具，生成高质量艺术作品和创意图像。",
    category: "AI工具",
    tags: ["AI工具", "设计绘图"],
    rating: 4.8,
    heat: 22700,
    trend: "+7.1%",
    logo: "🎨",
    logoBg: "bg-indigo-600",
  },
  {
    rank: 4,
    name: "Canva 可画",
    description: "在线设计平台，海量模板，轻松做出精美设计。",
    category: "设计工具",
    tags: ["设计工具"],
    rating: 4.8,
    heat: 21300,
    trend: "+8.2%",
    logo: "🖌️",
    logoBg: "bg-cyan-600",
  },
  {
    rank: 5,
    name: "Figma",
    description: "UI/UX 设计协作工具，支持实时协作与原型设计。",
    category: "设计工具",
    tags: ["设计工具"],
    rating: 4.8,
    heat: 18900,
    trend: "+6.3%",
    logo: "🎯",
    logoBg: "bg-purple-600",
  },
  {
    rank: 6,
    name: "GitHub",
    description: "全球领先的代码托管平台，支持开源协作与版本管理。",
    category: "开发工具",
    tags: ["开发工具"],
    rating: 4.9,
    heat: 15600,
    trend: "+5.7%",
    logo: "🐙",
    logoBg: "bg-gray-900",
  },
  {
    rank: 7,
    name: "Vercel",
    description: "前端应用部署与托管平台，专为现代 Web 打造。",
    category: "开发工具",
    tags: ["开发工具"],
    rating: 4.7,
    heat: 18900,
    trend: "+4.3%",
    logo: "▲",
    logoBg: "bg-black",
  },
  {
    rank: 8,
    name: "Pexels",
    description: "免费高清图片与视频素材库，适用于各类创意项目。",
    category: "设计素材",
    tags: ["设计素材"],
    rating: 4.8,
    heat: 13500,
    trend: "+3.2%",
    logo: "📸",
    logoBg: "bg-green-600",
  },
  {
    rank: 9,
    name: "Hugging Face",
    description: "领先的 AI 模型与数据集社区，探索和构建机器学习应用。",
    category: "AI工具",
    tags: ["AI工具"],
    rating: 4.8,
    heat: 12100,
    trend: "+6.8%",
    logo: "🤗",
    logoBg: "bg-yellow-600",
  },
  {
    rank: 10,
    name: "飞书文档",
    description: "多端协同的在线文档与知识库，团队协作更高效。",
    category: "效率办公",
    tags: ["效率办公"],
    rating: 4.8,
    heat: 17200,
    trend: "+7.1%",
    logo: "📋",
    logoBg: "bg-blue-600",
  },
];

export const trendingResources = [
  { rank: 1, name: "飞书文档", change: "+28.7%" },
  { rank: 2, name: "Vercel", change: "+22.8%" },
  { rank: 3, name: "Hugging Face", change: "+20.5%" },
  { rank: 4, name: "Pexels", change: "+17.3%" },
  { rank: 5, name: "Notion", change: "+16.9%" },
];

export const hotTags = [
  { name: "AI", count: 1024 },
  { name: "设计", count: 876 },
  { name: "开发", count: 1288 },
  { name: "效率", count: 1635 },
  { name: "学习", count: 882 },
  { name: "办公", count: 764 },
  { name: "编程", count: 598 },
  { name: "自动化", count: 398 },
  { name: "副业", count: 546 },
  { name: "模板", count: 421 },
  { name: "工具", count: 1756 },
  { name: "灵感", count: 387 },
];
